export const siteConfig = {
  name: "Anupam Baral",
  handle: "@gomugomucode",
  username: "gomugomucode",
  url: "https://anupambaral.com.np",
  ogImage: "https://anupambaral.com.np/og-image.webp",
  description:
    "Official portfolio of Anupam Baral (@gomugomucode), a Full-Stack Developer & AI Engineer in Nepal building React, Next.js, Python, and Solana Web3 systems.",
  primaryKeywords: [
    "Anupam Baral",
    "gomugomucode",
    "Full Stack Developer Nepal",
    "AI Engineer Nepal",
    "React Developer Nepal",
    "Next.js Developer",
    "TypeScript Developer",
    "Python Developer",
    "Solana Developer",
    "Software Engineer Nepal",
  ],
  secondaryKeywords: [
    "React Portfolio",
    "Next.js Portfolio",
    "AI ML Developer",
    "FastAPI Python",
    "Supabase Developer",
    "Open Source Developer",
    "Solana Web3",
  ],
  verification: {
    google: "",
    bing: "",
    clarity: "",
  },
  social: {
    github: "https://github.com/gomugomucode",
    linkedin: "https://linkedin.com/in/gomugomucode",
    twitter: "https://x.com/gomugomucode",
    medium: "https://medium.com/@gomugomucode",
    youtube: "https://youtube.com/@gomugomucode",
    googleMaps: "https://www.google.com/maps/place/Anupam+Baral+-+AI%2FML+%26+Full-Stack+Developer/@28.397455,84.1301506,7z/data=!3m1!4b1!4m6!3m5!1s0x85dbafd39ae92f89:0x13b3b1f0138c19d0!8m2!3d28.397455!4d84.1301506!16s%2Fg%2F11zc_q7f9c",
    facebook: "https://facebook.com/gomugomucode",
    instagram: "https://instagram.com/gomugomucode",
  },
  author: {
    name: "Anupam Baral",
    role: "Full Stack Developer & AI Engineer",
    location: "Butwal, Lumbini, Nepal",
    email: "contact@anupambaral.com.np",
    alternateEmail: "anupambaral.work@gmail.com",
  },
};
